# Generated by Django 3.1.5 on 2021-05-29 16:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TakeCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSpend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subdistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=100, null=True, verbose_name='Sub District Name')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.district', verbose_name='District Name')),
            ],
        ),
        migrations.CreateModel(
            name='MovementPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_m', models.CharField(max_length=200, null=True, verbose_name='From Where')),
                ('to_m', models.CharField(max_length=200, null=True, verbose_name='To Where')),
                ('sub_dristrict', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sub Dristrict Name')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('car_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Car Number')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.district', verbose_name='District Name')),
                ('move', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fuser.movetype')),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fuser.movementreason')),
                ('take_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fuser.takecar')),
                ('time_spand', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fuser.timespend')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.passuser')),
            ],
        ),
    ]
