# Generated by Django 3.1.5 on 2021-05-03 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=100, null=True, verbose_name='District name')),
            ],
        ),
        migrations.CreateModel(
            name='MovementReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subdistrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=100, null=True, verbose_name='Sub District Name')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fuser.district', verbose_name='District Name')),
            ],
        ),
        migrations.CreateModel(
            name='MovementPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_from', models.CharField(max_length=200, null=True, verbose_name='From Where')),
                ('_to', models.CharField(max_length=200, null=True, verbose_name='To Where')),
                ('time_spand', models.CharField(choices=[(1, 'One Hour'), (2, 'Two Hour'), (3, 'Three Hour'), (4, 'Four Hour'), (5, 'Six Hour'), (6, ' Eight Hour')], default=1, max_length=20, verbose_name='Time spending')),
                ('move', models.CharField(choices=[(1, 'Come and Go'), (2, 'Only Go')], default=1, max_length=20, verbose_name='Movement Type')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('take_car', models.BooleanField(default=False)),
                ('car_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Car Number')),
                ('drive', models.CharField(choices=[(1, 'Yes'), (2, ' No')], default=2, max_length=10, verbose_name='Drive Your self ?')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fuser.district', verbose_name='District Name')),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fuser.movementreason')),
                ('sub_dristrict', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fuser.subdistrict', verbose_name='Sub Dristrict Name')),
            ],
        ),
    ]
