# Generated by Django 3.1.5 on 2021-05-26 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='d_name',
            new_name='name',
        ),
    ]
