# Generated by Django 3.1.5 on 2021-05-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementpass',
            name='drive',
            field=models.CharField(choices=[('1', 'Yes'), ('2', ' No')], default='2', max_length=10, verbose_name='Drive Your self ?'),
        ),
        migrations.AlterField(
            model_name='movementpass',
            name='move',
            field=models.CharField(choices=[('1', 'Come and Go'), ('2', 'Only Go')], default='1', max_length=20, verbose_name='Movement Type'),
        ),
        migrations.AlterField(
            model_name='movementpass',
            name='time_spand',
            field=models.CharField(choices=[('1', 'One Hour'), ('2', 'Two Hour'), ('3', 'Three Hour'), ('4', 'Four Hour'), ('5', 'Six Hour'), ('6', ' Eight Hour')], default='1', max_length=20, verbose_name='Time spending'),
        ),
    ]
