# Generated by Django 3.1.5 on 2021-05-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementpass',
            name='traking_id',
        ),
        migrations.AlterField(
            model_name='movementpass',
            name='take_car',
            field=models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default='2', max_length=3, null=True),
        ),
    ]
