# Generated by Django 3.1.5 on 2021-05-30 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0001_initial'),
        ('fuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementpass',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.district', verbose_name='District Name'),
        ),
    ]
