# Generated by Django 3.1.5 on 2021-05-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0002_auto_20210503_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementpass',
            name='sub_dristrict',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sub Dristrict Name'),
        ),
    ]
