# Generated by Django 3.1.5 on 2021-05-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0002_auto_20210528_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movementpass',
            old_name='_from',
            new_name='from_m',
        ),
        migrations.RenameField(
            model_name='movementpass',
            old_name='_to',
            new_name='to_m',
        ),
    ]
