# Generated by Django 3.1.5 on 2021-05-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0002_auto_20210527_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='movementpass',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movementpass',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
