# Generated by Django 3.1.5 on 2021-05-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0003_auto_20210527_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementpass',
            name='time_spand',
            field=models.CharField(choices=[('1', 'One Hour'), ('2', 'Two Hour'), ('3', 'Three Hour'), ('4', 'Four Hour'), ('5', 'Six Hour'), ('6', ' Eight Hour')], max_length=20, verbose_name='Time spending'),
        ),
    ]
