# Generated by Django 3.1.5 on 2021-05-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0004_movementpass_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementpass',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
    ]
