# Generated by Django 3.1.5 on 2021-05-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0004_auto_20210530_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movetype',
            old_name='type',
            new_name='name',
        ),
    ]
