# Generated by Django 3.1.5 on 2021-05-30 14:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0001_initial'),
        ('fuser', '0005_auto_20210530_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementPassModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination_from', models.CharField(max_length=200, null=True, verbose_name='Destination From')),
                ('destination_to', models.CharField(max_length=200, null=True, verbose_name='Destination To')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('subdistrict_name', models.CharField(max_length=200, null=True, verbose_name='Subdistrict Name')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr/')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('district_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.district')),
                ('movement_reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fuser.movementreason')),
                ('movement_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fuser.movetype')),
                ('time_duration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fuser.timespend')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.passuser')),
            ],
            options={
                'verbose_name': 'Movement Pass',
                'verbose_name_plural': 'Movement Pass',
            },
        ),
    ]
