# Generated by Django 3.1.5 on 2021-05-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0006_movementpassmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementpassmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
