# Generated by Django 3.1.5 on 2021-05-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0007_auto_20210530_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementpassmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
