# Generated by Django 3.1.5 on 2021-05-30 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0008_auto_20210530_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement_type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Movement Type',
            },
        ),
    ]
