# Generated by Django 3.1.5 on 2021-05-30 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0009_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementpassmodel',
            name='movement_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fuser.movement_type'),
        ),
    ]
