# Generated by Django 3.1.5 on 2021-05-30 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0010_auto_20210530_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movement_type',
            options={'verbose_name': 'Movement Type', 'verbose_name_plural': 'Movement Type'},
        ),
    ]
