# Generated by Django 3.1.5 on 2021-05-31 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0011_auto_20210530_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementpass',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
