# Generated by Django 3.1.5 on 2021-05-31 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0012_auto_20210531_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementpassmodel',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='movementpassmodel',
            name='movement_reason',
        ),
        migrations.RemoveField(
            model_name='movementpassmodel',
            name='movement_type',
        ),
        migrations.RemoveField(
            model_name='movementpassmodel',
            name='time_duration',
        ),
        migrations.RemoveField(
            model_name='movementpassmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subdistrict',
            name='district',
        ),
        migrations.AlterModelOptions(
            name='movementreason',
            options={'verbose_name_plural': 'Movement Reason'},
        ),
        migrations.AlterModelOptions(
            name='movetype',
            options={'verbose_name_plural': 'Movement Type'},
        ),
        migrations.AlterModelOptions(
            name='timespend',
            options={'verbose_name_plural': 'Time Spending'},
        ),
        migrations.RemoveField(
            model_name='movementpass',
            name='car_number',
        ),
        migrations.RemoveField(
            model_name='movementpass',
            name='take_car',
        ),
        migrations.DeleteModel(
            name='Movement_type',
        ),
        migrations.DeleteModel(
            name='MovementPassModel',
        ),
        migrations.DeleteModel(
            name='Subdistrict',
        ),
        migrations.DeleteModel(
            name='TakeCar',
        ),
    ]
