# Generated by Django 3.1.5 on 2021-05-29 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='District name')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IDtype',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('thana', models.CharField(blank=True, max_length=200, null=True)),
                ('id_number', models.CharField(max_length=100, null=True, verbose_name='Id Number')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='profile')),
                ('is_admin', models.BooleanField(default=False)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.district')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.gender')),
                ('id_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.idtype', verbose_name='Id Name Type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
