# Generated by Django 3.1.5 on 2021-05-25 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passuser',
            name='idnumber',
        ),
        migrations.AddField(
            model_name='passuser',
            name='id_number',
            field=models.CharField(max_length=100, null=True, verbose_name='Id Number'),
        ),
        migrations.AlterField(
            model_name='passuser',
            name='id_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sadmin.idtype', verbose_name='Id Name Type'),
        ),
    ]
