# Generated by Django 3.1.5 on 2021-05-25 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0004_movementpass_traking_id'),
        ('sadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passuser',
            old_name='idtype',
            new_name='idnumber',
        ),
        migrations.AddField(
            model_name='passuser',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fuser.district'),
        ),
    ]
